import {Fragment} from "react";import {db} from "@/lib/db";import {requireSession} from "@/lib/auth";import {php,liters} from "@/lib/format";import {PageHeading} from "@/components/page-heading";import {monthLabel} from "@/lib/month-locks";import {getMonthNotes,MONTH_NOTE_MAX} from "@/lib/month-notes";import {MonthNotesModal,type MonthNoteRow} from "@/components/month-notes-modal";import Link from "next/link";import {MonthlyAmountChart} from "@/components/charts";import {ReportPrintButton} from "@/components/report-print-button";import {buildConsumption,monthsBetween,shiftMonth,shortMonth} from "@/lib/fuel-consumption";
type Q={month?:string;from?:string;to?:string};const isMonth=(value?:string)=>Boolean(value&&/^\d{4}-(0[1-9]|1[0-2])$/.test(value));
export default async function Page({searchParams}:{searchParams:Promise<Q>}){const s=await requireSession(),query=await searchParams;const canEdit=s.role==="ADMINISTRATOR"||s.role==="STAFF";const [monthly,notes]=await Promise.all([db.$queryRaw<{period:string;company:string;liters:unknown;amount:unknown;requested:unknown}[]>`SELECT DATE_FORMAT(t.transactionDate,'%Y-%m') period,c.code company,SUM(t.liters) liters,SUM(t.amount) amount,SUM(COALESCE(t.requestedAmount,0)) requested FROM FuelTransaction t LEFT JOIN Company c ON c.id=t.companyId WHERE t.organizationId=${s.organizationId} AND t.deletedAt IS NULL GROUP BY period,c.code ORDER BY period DESC,amount DESC`,getMonthNotes(s.organizationId)]);
  const noteFor=new Map(notes.map(note=>[note.month,note]));
  // Months with no transactions can still carry a note, so both sources are merged for the editor.
  const months=[...new Set([...monthly.map(row=>row.period),...notes.map(note=>note.month)])].sort((a,b)=>b.localeCompare(a));
  const noteRows:MonthNoteRow[]=months.map(month=>({month,label:monthLabel(month),note:noteFor.get(month)?.note??"",updatedByName:noteFor.get(month)?.updatedByName??""}));
  const periods=[...new Set(monthly.map(row=>row.period))];
  // The consumption report defaults to the latest month with fuel; the chart to the four months ending there.
  const month=isMonth(query.month)?query.month!:periods[0]??new Date().toISOString().slice(0,7);
  const chartTo=isMonth(query.to)?query.to!:month,chartFrom=isMonth(query.from)?query.from!:shiftMonth(chartTo,-3);
  const [year,index]=month.split("-").map(Number);
  const consumption=buildConsumption(await db.fuelTransaction.findMany({where:{organizationId:s.organizationId,deletedAt:null,transactionDate:{gte:new Date(year,index-1,1),lt:new Date(year,index,1)}},select:{liters:true,amount:true,fuelType:true,companyOriginal:true,vehicleOriginal:true,company:{select:{code:true}},vehicle:{select:{id:true,plateNumber:true,assetName:true,fuelType:true}}}}));
  const showOther=consumption.total.other>0,showUnspecified=consumption.total.unspecified>0;
  const monthTotals=new Map<string,number>();for(const row of monthly)monthTotals.set(row.period,(monthTotals.get(row.period)??0)+Number(row.amount));
  const chartMonths=monthsBetween(chartFrom,chartTo),chartData=chartMonths.map(item=>({month:shortMonth(item),Amount:Math.round((monthTotals.get(item)??0)*100)/100}));
  const chartTitle=`${monthLabel(chartMonths[0]).split(" ")[0]} to ${monthLabel(chartMonths[chartMonths.length-1])}`;
  const fuelLiters=(value:number)=>value?liters(value):"";
  return <><PageHeading title="Reports" description="Normalized monthly and semi-monthly business reporting." action={<MonthNotesModal months={noteRows} canEdit={canEdit} maxLength={MONTH_NOTE_MAX}/>}/><div className="grid md:grid-cols-3 gap-4 mb-6">{["Monthly fuel summary","Semi-monthly (1–15 / 16–end)","Usage by company & vehicle","Price-per-liter trend","Requested vs actual","Personal-use transactions","Vehicle fuel efficiency","Insurance expiration","AP / chargeback summary","Data-quality exceptions"].map(x=><div className="card" key={x}><strong>{x}</strong><p className="text-sm text-slate-500">Filterable database query · CSV/Excel-ready</p></div>)}</div><form className="card report-controls no-print mb-4"><label>Consumption month<select className="field" name="month" defaultValue={month}>{(periods.includes(month)?periods:[month,...periods]).map(item=><option key={item} value={item}>{monthLabel(item)}</option>)}</select></label><label>Chart from<input className="field" type="month" name="from" defaultValue={chartFrom}/></label><label>Chart to<input className="field" type="month" name="to" defaultValue={chartTo}/></label><button className="btn">Show</button></form>
    <section id="consumption-report" className="card desktop-table report-card mb-6"><div className="report-card-head"><div><h2 className="report-title">{monthLabel(month).toUpperCase()} FUEL Consumption of Company Vehicles</h2><p className="text-slate-500 m-0">For month of {monthLabel(month)}</p></div><ReportPrintButton target="consumption-report"/></div>
      {showUnspecified&&<p className="report-notice no-print">Some transactions have no fuel type, so their liters are listed under Unspecified. Set the fuel type on the transaction, or set Diesel or Gasoline on the vehicle in <Link href="/vehicles">Vehicles</Link>, to move them into the right column.</p>}
      <table className="table consumption-table"><thead><tr><th>Charging company</th><th>Vehicle</th><th className="num">Diesel</th><th className="num">Gasoline</th>{showOther&&<th className="num">Others</th>}{showUnspecified&&<th className="num">Unspecified</th>}<th className="num">Amount</th></tr></thead>
        <tbody>{consumption.groups.map(group=><Fragment key={group.company}>{group.rows.map((row,i)=><tr key={`${group.company}-${i}`} className={i===0?"company-start":undefined}><td>{i===0?group.company:""}</td><td>{row.vehicle}</td><td className="num">{fuelLiters(row.diesel)}</td><td className="num">{fuelLiters(row.gasoline)}</td>{showOther&&<td className="num">{fuelLiters(row.other)}</td>}{showUnspecified&&<td className="num">{fuelLiters(row.unspecified)}</td>}<td className="num">{php.format(row.amount)}</td></tr>)}</Fragment>)}</tbody>
        <tfoot><tr className="transaction-total-row"><th colSpan={2}>Overall total</th><th className="num">{liters(consumption.total.diesel)}</th><th className="num">{liters(consumption.total.gasoline)}</th>{showOther&&<th className="num">{liters(consumption.total.other)}</th>}{showUnspecified&&<th className="num">{liters(consumption.total.unspecified)}</th>}<th className="num">{php.format(consumption.total.amount)}</th></tr></tfoot></table>
      {!consumption.groups.length&&<p className="text-slate-500 p-6">No fuel transactions in {monthLabel(month)}.</p>}</section>
    <section id="monthly-chart-report" className="card report-card mb-6"><div className="report-card-head"><h2 className="report-title">Fuel Consumption of Company Vehicles Monitoring from {chartTitle}</h2><ReportPrintButton target="monthly-chart-report"/></div><MonthlyAmountChart data={chartData}/></section>
    <div id="monthly-summary-report" className="card desktop-table report-card"><h2 className="font-bold">Monthly summary</h2><table className="table"><thead><tr><th>Month</th><th>Company</th><th>Liters</th><th>Actual</th><th>Requested</th><th>Variance</th></tr></thead><tbody>{periods.map(period=>{const rows=monthly.filter(row=>row.period===period),note=noteFor.get(period);
    return <Fragment key={period}><tr className="month-group-row"><th colSpan={6}><span>{monthLabel(period)}</span>{note?<em className="month-group-note">{note.note}</em>:<em className="month-group-note is-empty">No month note</em>}</th></tr>
      {rows.map((r,i)=><tr key={`${period}-${i}`}><td>{r.period}</td><td>{r.company??"Unmapped"}</td><td>{liters(String(r.liters))}</td><td>{php.format(Number(r.amount))}</td><td>{php.format(Number(r.requested))}</td><td>{php.format(Number(r.requested)-Number(r.amount))}</td></tr>)}</Fragment>})}</tbody></table>{!monthly.length&&<p className="text-slate-500 p-6">Import transactions to populate reports.</p>}</div></>}
