"use server";
import type {Role} from "@prisma/client";
import bcrypt from "bcryptjs";
import {db} from "@/lib/db";
import {requireSession} from "@/lib/auth";
import {revalidatePath} from "next/cache";

const roles:Role[]=["ADMINISTRATOR","STAFF","APPROVER","VIEWER"];
export async function saveUser(id:string|null,data:FormData){const session=await requireSession(["ADMINISTRATOR"]),name=String(data.get("name")??"").trim(),email=String(data.get("email")??"").trim().toLowerCase(),role=String(data.get("role")??"") as Role,password=String(data.get("password")??""),passwordConfirmation=String(data.get("passwordConfirmation")??""),active=data.get("active")==="on";if(!name||!email||!roles.includes(role))return{ok:false,error:"Name, email, and a valid role are required"};if(!id&&password.length<8)return{ok:false,error:"New users require a password of at least 8 characters"};if(password&&password.length<8)return{ok:false,error:"Password must contain at least 8 characters"};if(password!==passwordConfirmation)return{ok:false,error:"Password confirmation does not match"};if(id===session.userId&&(!active||role!=="ADMINISTRATOR"))return{ok:false,error:"You cannot deactivate or remove Administrator access from your own account"};try{const before=id?await db.user.findFirst({where:{id,organizationId:session.organizationId}}):null;if(id&&!before)return{ok:false,error:"User not found"};const passwordHash=password?await bcrypt.hash(password,12):undefined;const user=id?await db.user.update({where:{id},data:{name,email,role,active,...(passwordHash?{passwordHash}:{})}}):await db.user.create({data:{organizationId:session.organizationId,name,email,role,active,passwordHash:passwordHash!}});await db.auditLog.create({data:{userId:session.userId,action:id?"UPDATE_USER":"CREATE_USER",entityType:"User",entityId:user.id,beforeValue:before?JSON.parse(JSON.stringify({...before,passwordHash:"[REDACTED]"})):undefined,afterValue:{name,email,role,active,passwordChanged:Boolean(password)}}});revalidatePath("/users");return{ok:true,error:""}}catch(error){return{ok:false,error:error instanceof Error&&error.message.includes("Unique constraint")?"That email address is already in use":"Unable to save the user"}}}
export async function changeOwnPassword(data:FormData){const session=await requireSession(),currentPassword=String(data.get("currentPassword")??""),password=String(data.get("password")??""),confirmation=String(data.get("passwordConfirmation")??"");if(password.length<8)return{ok:false,error:"New password must contain at least 8 characters"};if(password!==confirmation)return{ok:false,error:"Password confirmation does not match"};const user=await db.user.findFirst({where:{id:session.userId,organizationId:session.organizationId,active:true}});if(!user)return{ok:false,error:"User account not found"};if(session.role!=="ADMINISTRATOR"&&!(await bcrypt.compare(currentPassword,user.passwordHash)))return{ok:false,error:"Existing password is incorrect"};await db.$transaction([db.user.update({where:{id:user.id},data:{passwordHash:await bcrypt.hash(password,12)}}),db.auditLog.create({data:{userId:user.id,action:"CHANGE_PASSWORD",entityType:"User",entityId:user.id,afterValue:{passwordChanged:true,administratorBypass:session.role==="ADMINISTRATOR"}}})]);return{ok:true,error:""}}
export async function deleteUser(id:string,confirmation:string){const session=await requireSession(["ADMINISTRATOR"]);if(confirmation!=="DELETE")return{ok:false,error:"Type DELETE exactly to confirm"};if(id===session.userId)return{ok:false,error:"You cannot delete your own signed-in account"};const user=await db.user.findFirst({where:{id,organizationId:session.organizationId}});if(!user)return{ok:false,error:"User not found"};try{await db.$transaction(async transaction=>{await transaction.user.delete({where:{id}});await transaction.auditLog.create({data:{userId:session.userId,action:"DELETE_USER",entityType:"User",entityId:id,beforeValue:{name:user.name,email:user.email,role:user.role,active:user.active}}})});revalidatePath("/users");return{ok:true,error:""}}catch{return{ok:false,error:"This user has operational or audit history and cannot be deleted. Mark the account inactive instead."}}}
